#!/bin/bash

# We only want to run the script if the board has RGB capability
if ! knulli-board-capability "rgb"; then
    exit 1
fi

case "$1" in
  start)
  # Code in here will only be executed on start.
    cd /userdata/roms/tools/hh-prime-rgb
    nohup python rgb_daemon.py &>/userdata/rgbled.log &
    ;;
  stop)
    # Code in here will only be executed on shutdown.
    curl -s "http://localhost:1235/kill"
    ;;
  restart)
    # Code in here will only be executed on shutdown.
    curl -s "http://localhost:1235/kill"
    sleep 2
    cd /userdata/roms/tools/hh-prime-rgb
    nohup python rgb_daemon.py &>/userdata/rgbled.log &
    ;;
  *)
    # Code in here will be executed in all other conditions.
    echo "Usage: $0 {start|stop}"
    ;;
esac

exit $?
